// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/catalog.proto

package catalog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCarTypesResponse struct {
	CarTypes             []*CarType `protobuf:"bytes,1,rep,name=carTypes,proto3" json:"carTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCarTypesResponse) Reset()         { *m = ListCarTypesResponse{} }
func (m *ListCarTypesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCarTypesResponse) ProtoMessage()    {}
func (*ListCarTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5454e87d652be236, []int{0}
}

func (m *ListCarTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarTypesResponse.Unmarshal(m, b)
}
func (m *ListCarTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarTypesResponse.Marshal(b, m, deterministic)
}
func (m *ListCarTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarTypesResponse.Merge(m, src)
}
func (m *ListCarTypesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCarTypesResponse.Size(m)
}
func (m *ListCarTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarTypesResponse proto.InternalMessageInfo

func (m *ListCarTypesResponse) GetCarTypes() []*CarType {
	if m != nil {
		return m.CarTypes
	}
	return nil
}

type CarType struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarType) Reset()         { *m = CarType{} }
func (m *CarType) String() string { return proto.CompactTextString(m) }
func (*CarType) ProtoMessage()    {}
func (*CarType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5454e87d652be236, []int{1}
}

func (m *CarType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarType.Unmarshal(m, b)
}
func (m *CarType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarType.Marshal(b, m, deterministic)
}
func (m *CarType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarType.Merge(m, src)
}
func (m *CarType) XXX_Size() int {
	return xxx_messageInfo_CarType.Size(m)
}
func (m *CarType) XXX_DiscardUnknown() {
	xxx_messageInfo_CarType.DiscardUnknown(m)
}

var xxx_messageInfo_CarType proto.InternalMessageInfo

func (m *CarType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CarType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5454e87d652be236, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListCarTypesResponse)(nil), "ListCarTypesResponse")
	proto.RegisterType((*CarType)(nil), "CarType")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() {
	proto.RegisterFile("protos/catalog.proto", fileDescriptor_5454e87d652be236)
}

var fileDescriptor_5454e87d652be236 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x4e, 0x2c, 0x49, 0xcc, 0xc9, 0x4f, 0xd7, 0x03, 0x73, 0x95, 0x6c, 0xb8,
	0x44, 0x7c, 0x32, 0x8b, 0x4b, 0x9c, 0x13, 0x8b, 0x42, 0x2a, 0x0b, 0x52, 0x8b, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x54, 0xb8, 0x38, 0x92, 0xa1, 0x62, 0x12, 0x8c, 0x0a, 0xcc,
	0x1a, 0xdc, 0x46, 0x1c, 0x7a, 0x50, 0x45, 0x41, 0x70, 0x19, 0x25, 0x5d, 0x2e, 0x76, 0xa8, 0xa0,
	0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a,
	0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x13, 0x58, 0x04, 0xcc, 0x56, 0x62, 0xe7,
	0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x34, 0x72, 0xe5, 0x12, 0x72, 0x2c, 0x2d, 0xc9, 0x77, 0x86,
	0x38, 0x25, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x9f, 0x8b, 0x07, 0xd9, 0x2d, 0x42,
	0x6c, 0x7a, 0x60, 0xd5, 0x52, 0xa2, 0x7a, 0xd8, 0x9c, 0xa8, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x83,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xb7, 0xc9, 0x49, 0xdb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AutoCatalogServiceClient is the client API for AutoCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoCatalogServiceClient interface {
	ListCarTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCarTypesResponse, error)
}

type autoCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutoCatalogServiceClient(cc grpc.ClientConnInterface) AutoCatalogServiceClient {
	return &autoCatalogServiceClient{cc}
}

func (c *autoCatalogServiceClient) ListCarTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCarTypesResponse, error) {
	out := new(ListCarTypesResponse)
	err := c.cc.Invoke(ctx, "/AutoCatalogService/ListCarTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCatalogServiceServer is the server API for AutoCatalogService service.
type AutoCatalogServiceServer interface {
	ListCarTypes(context.Context, *Empty) (*ListCarTypesResponse, error)
}

// UnimplementedAutoCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAutoCatalogServiceServer struct {
}

func (*UnimplementedAutoCatalogServiceServer) ListCarTypes(ctx context.Context, req *Empty) (*ListCarTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarTypes not implemented")
}

func RegisterAutoCatalogServiceServer(s *grpc.Server, srv AutoCatalogServiceServer) {
	s.RegisterService(&_AutoCatalogService_serviceDesc, srv)
}

func _AutoCatalogService_ListCarTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).ListCarTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AutoCatalogService/ListCarTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).ListCarTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AutoCatalogService",
	HandlerType: (*AutoCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCarTypes",
			Handler:    _AutoCatalogService_ListCarTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/catalog.proto",
}
